In [1]:
import numpy as np
import pandas as pd

In [2]:
matches = pd.read_csv("IPL Matches 2008-2020.csv")
deliveries = pd.read_csv("IPL Ball-by-Ball 2008-2020.csv")

In [3]:
matches.head()#team1 is the batting team in 2nd innings

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [4]:
deliveries.head()

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore

In [5]:
matches.shape

(816, 17)

In [6]:
deliveries.shape

(193468, 18)

In [7]:
#to calc. total runs
deliveries.groupby(['id', 'inning']).sum()['total_runs'].reset_index()

           id  inning  total_runs
0      335982       1         222
1      335982       2          82
2      335983       1         240
3      335983       2         207
4      335984       1         129
...       ...     ...         ...
1625  1237178       2         132
1626  1237180       1         189
1627  1237180       2         172
1628  1237181       1         156
1629  1237181       2         157

[1630 rows x 3 columns]

In [8]:
total_score_ds = deliveries.groupby(['id', 'inning']).sum()['total_runs'].reset_index()

In [9]:
total_score_ds = total_score_ds[total_score_ds['inning']==1]#since, we want to pred. in the 2nd innings itself.

In [10]:
total_score_ds

           id  inning  total_runs
0      335982       1         222
2      335983       1         240
4      335984       1         129
6      335985       1         165
8      335986       1         110
...       ...     ...         ...
1620  1216547       1         201
1622  1237177       1         200
1624  1237178       1         131
1626  1237180       1         189
1628  1237181       1         156

[816 rows x 3 columns]

In [11]:
matches.merge(total_score_ds[['id', 'total_runs']], left_on='id', right_on='id')

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,total_runs
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen,222
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri,240
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar,129
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper,165
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel,201
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon,200
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi,131
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi,189
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon,156

In [12]:
matches = matches.merge(total_score_ds[['id', 'total_runs']], left_on='id', right_on='id')

In [13]:
matches['team1'].unique()#we need to remove teams who are not playing right now.

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [14]:
#forming a list, which is to be there in the dataset.
teams=[
    'Royal Challengers Bangalore', 
    'Kings XI Punjab',
    'Mumbai Indians',
    'Kolkata Knight Riders',
    'Rajasthan Royals', 
    'Chennai Super Kings',
    'Sunrisers Hyderabad',
    'Delhi Capitals'
]

In [15]:
matches['team1']=matches['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
matches['team2']=matches['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')

In [16]:
matches['team1']=matches['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
matches['team2']=matches['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [17]:
matches=matches[matches['team1'].isin(teams)]
matches=matches[matches['team2'].isin(teams)]

In [18]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Chennai Super Kings'], dtype=object)

In [19]:
matches.shape

(701, 18)

In [20]:
matches

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,total_runs
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen,222
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri,240
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar,129
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper,165
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel,201
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon,200
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi,131
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi,189
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon,156

In [28]:
matches = matches[['id', 'venue', 'total_runs', 'winner']]

In [29]:
matches

,id,venue,total_runs,winner
0,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders
1,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings
2,335984,Feroz Shah Kotla,129,Delhi Daredevils
3,335985,Wankhede Stadium,165,Royal Challengers Bangalore
4,335986,Eden Gardens,110,Kolkata Knight Riders
...,...,...,...,...
811,1216547,Dubai International Cricket Stadium,201,Royal Challengers Bangalore
812,1237177,Dubai International Cricket Stadium,200,Mumbai Indians
813,1237178,Sheikh Zayed Stadium,131,Sunrisers Hyderabad
814,1237180,Sheikh Zayed Stadium,189,Delhi Capitals
815,1237181,Dubai International Cricket Stadium,156,Mumbai Indians

In [37]:
delivery = matches.merge(deliveries, on='id')

In [38]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,extra_runs,total_runs_y,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,1,6,5,RT Ponting,BB McCullum,AA Noffke,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,1,6,6,BB McCullum,RT Ponting,AA Noffke,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,1,7,1,BB McCullum,RT Ponting,Z Khan,...,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,1,7,2,BB McCullum,RT Ponting,Z Khan,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,1,7,3,RT Ponting,BB McCullum,Z Khan,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166457,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,...,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
166458,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
166459,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,1,13,1,RR Pant,SS Iyer,KH Pandya,...,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
166460,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,1,13,2,RR Pant,SS Iyer,KH Pandya,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
166461,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,1,13,3,SS Iyer,RR Pant,KH Pandya,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [34]:
delivery['inning'].unique()

array([1, 2], dtype=int64)

In [46]:
delivery = delivery[delivery['inning']==2]

In [47]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,total_runs_y,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score
121,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,0,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,214
122,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,1,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,215
123,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,1,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,216
124,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,1,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,217
125,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,0,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,197
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,198
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,199
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,0,0,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,199
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,200

In [48]:
delivery['current_score'] = delivery.groupby('id').cumsum()['total_runs_y']

C:\Users\Dell\AppData\Local\Temp\ipykernel_15280\889714514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery['current_score'] = delivery.groupby('id').cumsum()['total_runs_y']

In [50]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,total_runs_y,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score
121,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,0,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,0
122,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,1,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1
123,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,1,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2
124,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,1,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,3
125,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,0,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,0,0,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157

In [54]:
delivery['runs_left']=delivery['total_runs_x']-delivery['current_score']+1

C:\Users\Dell\AppData\Local\Temp\ipykernel_15280\2250377590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery['runs_left']=delivery['total_runs_x']-delivery['current_score']+1

In [55]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_left
121,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,0,223
122,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222
123,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221
124,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,3,220
125,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,0,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0

In [72]:
delivery['balls_left'] = 126 - ((delivery['over']+1)*6 + delivery['ball'])

C:\Users\Dell\AppData\Local\Temp\ipykernel_15280\189073767.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery['balls_left'] = 126 - ((delivery['over']+1)*6 + delivery['ball'])

In [73]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left,CRR
225,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,1,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,119,10,-4.800000
226,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,2,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,118,10,-6.000000
229,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,5,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,115,10,-24.000000
230,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,6,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,8,233,114,10,inf
231,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,1,1,K Goel,JR Hopes,MS Gony,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,9,232,113,10,54.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,12,6,9.058824
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,11,6,9.029126
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,10,6,9.000000
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,9,5,8.914286
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,8,5,8.886792

In [59]:
#to obtain wickets left
wickets = delivery.groupby('id').cumsum()['is_wicket'].values
delivery['wicket_left']=10-wickets

C:\Users\Dell\AppData\Local\Temp\ipykernel_15280\2166069136.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery['wicket_left']=10-wickets

In [60]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left
121,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,0,223,88,10
122,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222,87,10
123,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,86,10
124,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,85,10
125,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,84,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,18,6
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,17,6
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,16,6
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,15,5
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,14,5

In [74]:
#to obtain CRR
delivery['CRR'] = delivery['current_score']*6/(120-delivery['balls_left'])

C:\Users\Dell\AppData\Local\Temp\ipykernel_15280\2764142986.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery['CRR'] = delivery['current_score']*6/(120-delivery['balls_left'])

In [69]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left,CRR
121,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,2,CL White,MV Boucher,AB Agarkar,...,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,0,223,88,10,0.000000
122,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,3,CL White,MV Boucher,AB Agarkar,...,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222,87,10,0.181818
123,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,4,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,86,10,0.352941
124,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,5,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,85,10,0.514286
125,335982,M Chinnaswamy Stadium,222,Kolkata Knight Riders,2,6,6,MV Boucher,CL White,AB Agarkar,...,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,84,10,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,18,6,9.058824
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,17,6,9.029126
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,16,6,9.000000
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,15,5,8.914286
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,14,5,8.886792

In [75]:
id_to_drop = 335982 #not complete info. for this dataset
delivery = delivery[delivery['id'] != id_to_drop]

In [76]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left,CRR
225,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,1,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,119,10,24.000000
226,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,2,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,118,10,12.000000
229,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,5,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,115,10,4.800000
230,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,6,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,8,233,114,10,8.000000
231,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,1,1,K Goel,JR Hopes,MS Gony,...,NaN,NaN,NaN,Kings XI Punjab,Chennai Super Kings,9,232,113,10,7.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,12,6,8.555556
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,11,6,8.532110
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,10,6,8.509091
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,9,5,8.432432
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,8,5,8.410714

In [77]:
#to obtain RRR
delivery['RRR'] = delivery['runs_left']*6/delivery['balls_left']

In [78]:
delivery

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,fielder,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left,CRR,RRR
225,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,1,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,119,10,24.000000,11.949580
226,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,2,K Goel,JR Hopes,JDP Oram,...,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,118,10,12.000000,12.050847
229,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,5,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,Kings XI Punjab,Chennai Super Kings,4,237,115,10,4.800000,12.365217
230,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,6,JR Hopes,K Goel,JDP Oram,...,NaN,NaN,Kings XI Punjab,Chennai Super Kings,8,233,114,10,8.000000,12.263158
231,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,1,1,K Goel,JR Hopes,MS Gony,...,NaN,NaN,Kings XI Punjab,Chennai Super Kings,9,232,113,10,7.714286,12.318584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166366,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,17,6,HH Pandya,Ishan Kishan,K Rabada,...,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,12,6,8.555556,1.500000
166367,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,1,HH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,11,6,8.532110,1.090909
166368,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,2,Ishan Kishan,HH Pandya,A Nortje,...,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,10,6,8.509091,0.600000
166369,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,3,HH Pandya,Ishan Kishan,A Nortje,...,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,9,5,8.432432,0.666667
166370,1237181,Dubai International Cricket Stadium,156,Mumbai Indians,2,18,4,KH Pandya,Ishan Kishan,A Nortje,...,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,8,5,8.410714,0.000000

In [79]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [82]:
delivery['result'] = delivery.apply(result, axis=1)

In [84]:
delivery.head()

,id,venue,total_runs_x,winner,inning,over,ball,batsman,non_striker,bowler,...,extras_type,batting_team,bowling_team,current_score,runs_left,balls_left,wicket_left,CRR,RRR,result
225,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,1,K Goel,JR Hopes,JDP Oram,...,NaN,Kings XI Punjab,Chennai Super Kings,4,237,119,10,24.000000,11.949580,0
226,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,2,K Goel,JR Hopes,JDP Oram,...,NaN,Kings XI Punjab,Chennai Super Kings,4,237,118,10,12.000000,12.050847,0
229,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,5,JR Hopes,K Goel,JDP Oram,...,NaN,Kings XI Punjab,Chennai Super Kings,4,237,115,10,4.800000,12.365217,0
230,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,0,6,JR Hopes,K Goel,JDP Oram,...,NaN,Kings XI Punjab,Chennai Super Kings,8,233,114,10,8.000000,12.263158,0
231,335983,"Punjab Cricket Association Stadium, Mohali",240,Chennai Super Kings,2,1,1,K Goel,JR Hopes,MS Gony,...,NaN,Kings XI Punjab,Chennai Super Kings,9,232,113,10,7.714286,12.318584,0

In [87]:
final = delivery[['batting_team', 'bowling_team', 'venue', 'runs_left', 'balls_left', 'wicket_left', 'total_runs_x', 'CRR', 'RRR', 'result']]

In [88]:
final = final.sample(final.shape[0])

In [116]:
final.dropna(inplace=True)

In [125]:
final = final[final['balls_left']!=0]

In [126]:
final

,batting_team,bowling_team,venue,runs_left,balls_left,wicket_left,total_runs_x,CRR,RRR,result
57888,Rajasthan Royals,Royal Challengers Bangalore,Sawai Mansingh Stadium,184,2,10,189,0.305085,552.000000,0
88054,Royal Challengers Bangalore,Kings XI Punjab,M Chinnaswamy Stadium,60,85,2,198,23.828571,4.235294,0
34356,Deccan Chargers,Kolkata Knight Riders,Eden Gardens,50,91,5,181,27.310345,3.296703,0
109059,Mumbai Indians,Kolkata Knight Riders,Eden Gardens,156,94,10,187,7.384615,9.957447,1
41803,Kolkata Knight Riders,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",17,9,6,153,7.405405,11.333333,0
...,...,...,...,...,...,...,...,...,...,...
19498,Royal Challengers Bangalore,Mumbai Indians,New Wanderers Stadium,89,51,9,149,5.304348,10.470588,1
152360,Kings XI Punjab,Delhi Capitals,Dubai International Cricket Stadium,125,117,6,157,66.000000,6.410256,0
112049,Royal Challengers Bangalore,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",107,30,7,194,5.866667,21.400000,0
30738,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",128,41,8,136,0.683544,18.731707,0
154264,Chennai Super Kings,Kolkata Knight Riders,Sheikh Zayed Stadium,56,20,7,167,6.720000,16.800000,0

In [127]:
X=final.iloc[:,:-1]
y=final.iloc[:,-1]

In [128]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [129]:
X_train

,batting_team,bowling_team,venue,runs_left,balls_left,wicket_left,total_runs_x,CRR,RRR
54989,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",67,101,7,205,43.894737,3.980198
61887,Royal Challengers Bangalore,Mumbai Indians,Wankhede Stadium,121,97,10,141,5.478261,7.484536
137812,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",38,66,9,70,3.666667,3.454545
74110,Sunrisers Hyderabad,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal",9,90,7,129,24.200000,0.600000
116398,Royal Challengers Bangalore,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",61,19,5,207,8.732673,19.263158
...,...,...,...,...,...,...,...,...,...
95537,Kings XI Punjab,Rajasthan Royals,Maharashtra Cricket Association Stadium,124,95,8,162,9.360000,7.831579
18299,Kolkata Knight Riders,Mumbai Indians,Buffalo Park,51,14,8,148,5.547170,21.857143
75549,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,84,54,8,161,7.090909,9.333333
40221,Delhi Daredevils,Deccan Chargers,Feroz Shah Kotla,139,9,10,145,0.378378,92.666667
106975,Chennai Super Kings,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",22,77,7,130,15.209302,1.714286

In [130]:
#since, three columns are string, so we need to apply OneHotencoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse=False, drop='first'), ['batting_team', 'bowling_team', 'venue'])], 
    remainder='passthrough')

In [137]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [142]:
pipe = Pipeline(steps=[('step1', trf),
               ('step2', LogisticRegression(solver='liblinear'))])

In [143]:
pipe.fit(X_train, y_train)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [144]:
y_pred=pipe.predict(X_test)

In [145]:
accuracy_score(y_test,y_pred)

0.8093154110659581

In [148]:
pipe.predict_proba(X_test)[98]

array([0.97694678, 0.02305322])